apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: contour
  name: contour
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: contour
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contour
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
        prometheus.io/path: "/stats"
        prometheus.io/format: "prometheus"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ingress.kirkcloud.com/class
                operator: In
                values:
                - envoy
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      hostNetwork: true
      imagePullSecrets:
      - name: hub.qiniu.com
      containers:
      - image: reg.qiniu.com/u-1381168308-default/contour:v0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
          name: contour
        name: contour
        command: ["contour"]
        args: ["serve", "--incluster", "--envoy-http-port=80", "--envoy-https-port=443"]
      - image: reg.qiniu.com/u-1381168308-default/envoy-alpine:v1.6.0
        name: envoy
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        command: ["envoy"]
        args: ["-c", "/config/contour.yaml", "--service-cluster", "cluster0", "--service-node", "node0", "-l", "debug", "--v2-config-only"]
        volumeMounts:
        - name: contour-config
          mountPath: /config
      initContainers:
      - image: reg.qiniu.com/u-1381168308-default/contour:v0.4
        imagePullPolicy: Always
        name: envoy-initconfig
        command: ["contour"]
        args: ["bootstrap", "/config/contour.yaml"]
        volumeMounts:
        - name: contour-config
          mountPath: /config
#        volumeMounts:
#        - mountPath: /config/envoy.yaml
#          name: envoy-config
#          readOnly: true
      volumes:
      - name: contour-config
        emptyDir: {}
#      - configMap:
#          name: envoy-config
#        name: envoy-config
      dnsPolicy: ClusterFirst
      serviceAccountName: contour
      terminationGracePeriodSeconds: 30
